# File: .github/workflows/build-and-push.yml (Corrected for Lowercase)

name: Build and Push Docker Images on Merge to Main

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # REMOVED an IMAGE_NAME from here, as we will create a sanitized one in the job.

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW STEP ADDED HERE ---
      # This step takes the GitHub repository variable (e.g., "AayzStha37/personal-portfolio"),
      # converts it to all lowercase, and saves it to a new environment variable named IMAGE_NAME.
      - name: Sanitize repository name for Docker tag
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push portfolio-api image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          # --- UPDATED THIS LINE ---
          # Use the new, sanitized, lowercase IMAGE_NAME variable.
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:latest

      - name: Build and push portfolio-ui image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          # --- UPDATED THIS LINE ---
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ui:latest