# File: .github/workflows/build-and-push.yml

name: Build and Push Docker Images

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs in this workflow
env:
  # The GitHub Container Registry to push to
  REGISTRY: ghcr.io
  # The name of the image will be derived from your repository name, e.g., ghcr.io/your-username/my-portfolio
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to write to the registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # The GITHUB_TOKEN is a special, automatically-provided secret for authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        # This action sets up the Docker builder instance used by the next steps
        uses: docker/setup-buildx-action@v3

      # This step builds AND pushes the Java Backend image
      - name: Build and push portfolio-api image
        uses: docker/build-push-action@v5
        with:
          context: ./api # The path to the 'api' Dockerfile directory
          file: ./api/Dockerfile
          push: true # This flag tells the action to push after building
          # These tags will be applied to the image. e.g., ghcr.io/your-username/my-portfolio/api:latest
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:latest

      # This step builds AND pushes the React Frontend image
      - name: Build and push portfolio-ui image
        uses: docker/build-push-action@v5
        with:
          context: ./ui # The path to the 'ui' Dockerfile directory
          file: ./ui/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ui:latest